language: node_js
node_js:
      - "6.2.2"
git:
submodules: false
install:
      - npm install
test:
      - npm run test
services:
      - mysql


before_install:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS user;'
      - mysql -e 'use user;CREATE TABLE User
                           (
                           id INT(4) auto_increment primary key,
                           username varchar(255)  NOT NULL,
                           name varchar(255)  NOT NULL,
                           age INT NOT NULL DEFAULT 0,
                           sex varchar(4)  NOT NULL,
                           phone varchar(255)  NOT NULL,
                           email varchar(255)  NOT NULL,
                           note varchar(255)  NOT NULL,
                           )'