language: node_js
node_js:
      - "6.2.2"
git:
submodules: false
install:
      - npm install
test:
      - npm run test
services:
      - mysql


before_install:
      - mysql -e 'CREATE DATABASE IF NOT EXISTS user;'
      - mysql -e 'use user;CREATE TABLE User
                           (
                           id INT(4) auto_increment primary key,
                           username char(20)  NOT NULL,
                           name char(20)  NOT NULL,
                           age INT(4) NOT NULL ,
                           sex char(20)  NOT NULL,
                           phone char(11)  NOT NULL,
                           email char(40)  NOT NULL,
                           note char(60),
                           )'